const user = [
    {
        id: "1",
        sourceCoverPhoto: "src/images/tweet-image.png",
        sourceprofilePicture: "src/images/profile-photo.png",
        avatar: "src/images/profile-photo.png",
        name: "Bradley Ortiz",
        username: "@bradley_",
        post: "25",
        bio: "I'm a software engineer from Kinshasa, Congo.",
        location: "Kinshasa, Congo",
        websiteLink: "www.newyork.com",
        joinedDate: "Joined November 2023",
        followers: 10,
        following: 250,
    },
    {
        id: "2",
        sourceCoverPhoto: "src/images/tweet-image.png",
        sourceprofilePicture: "src/images/profile-photo.png",
        avatar: "src/images/profile-photo.png",
        name: "CNN",
        username: "@CNN",
        post: "25",
        bio: "I'm a software .",
        location: "Kinshasa, Congo",
        websiteLink: "www.newyork.com",
        joinedDate: "Joined November 2023",
        followers: 700,
        following: 350,
    },
    {
        id: "3",
        sourceCoverPhoto: "src/images/tweet-image.png",
        sourceprofilePicture: "src/images/profile-photo.png",
        avatar: "src/images/profile-photo.png",
        name: "Twitter",
        username: "@Twitter",
        post: "25",
        bio: " from Kinshasa, Congo.",
        location: "Kinshasa, Congo",
        websiteLink: "www.newyork.com",
        joinedDate: "Joined November 2023",
        followers: 30,
        following: 600,
    },
    {
        id: "4",
        sourceCoverPhoto: "src/images/tweet-image.png",
        sourceprofilePicture: "src/images/profile-photo.png",
        avatar: "src/images/profile-photo.png",
        name: "The New York Times",
        username: "@nytimes",
        post: "25",
        bio: " from Kinshasa, Congo.",
        location: "Kinshasa, Congo",
        websiteLink: "www.newyork.com",
        joinedDate: "Joined November 2023",
        followers: 10,
        following: 51,
    },
];

export default user;
