const user = [
    {
        id: "1",
        sourceCoverPhoto: "src/images/tweet-image.png",
        sourceprofilePicture: "src/images/profile-photo.png",
        name: "Bradley Ortiz",
        username: "@bradley_",
        post: "15",
        bio: "I'm a software engineer from Kinshasa, Congo.",
        location: "Kinshasa, Congo",
        websiteLink: "www.newyork.com",
        joinedDate: "Joined November 2023",
        followers: 10,
        following: 60,
    },
    {
        id: "2",
        sourceCoverPhoto: "src/images/tweet-image.png",
        sourceprofilePicture: "src/images/tweet-profile-photo.png",
        name: "CNN",
        username: "@CNN",
        post: "35",
        bio: "I'm a software webdesigner from Kinshasa, Congo.",
        sourceprofilePicture: "src/images/profile-photo.png",
        avatar: "src/images/profile-photo.png",
        name: "CNN",
        username: "@CNN",
        post: "25",
        bio: "I'm a software .",
        location: "Kinshasa, Congo",
        websiteLink: "www.newyork.com",
        joinedDate: "Joined November 2023",
        followers: 500,
        following: 500,
    },
    {
        id: "3",
        sourceCoverPhoto: "src/images/tweet-image.png",
        sourceprofilePicture: "src/images/image2.svg",
        name: "Twitter",
        username: "@Twitter",
        post: "5",
        bio: " I'm a develloper fulstack from Kinshasa, Congo..",
        location: "Kinshasa, Congo",
        websiteLink: "www.newyork.com",
        joinedDate: "Joined November 2023",
        followers: 100,
        following: 500,
    },
    {
        id: "4",
        sourceCoverPhoto: "src/images/tweet-image.png",
        sourceprofilePicture: "src/images/image 1.svg",
        name: "The New York Times",
        username: "@nytimes",
        post: "10",
        bio: "I'm a lead dev from Brazza.",
        post: "25",
        bio: " from Kinshasa, Congo.",
        location: "Kinshasa, Congo",
        websiteLink: "www.newyork.com",
        joinedDate: "Joined November 2023",
        followers: 100,
        following: 500,
    },
];

export default user;
